apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kubeflow-ingressgateway-certs
  namespace: istio-system
spec:
  secretName: kubeflow-ingressgateway-certs
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: kubeflow.kubeflow.lukemarsden.net
  dnsNames:
    - kubeflow.kubeflow.lukemarsden.net
