kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
    data: null
  encryptedData:
    admin-password: AgAvmUP7wMybuSSQIoMZEcqeerAqMZUEMPvSYSZsVqJGcd+kaJVOWjNwHmVdcudlr6gDCPZQ4dChoTnXPeFLLsEGAWzb0MLT9PmyptEax1kpFYA3Evw3V8MoHzxRwPdGeYgwFa5W8nP4UT8t7J7CJephjB5p/gouqjiysJHPo1iHlJL+dG6DU/e7l7MAqKHryGL79UnN9xpZoSWCqoUT8sqhHtCrp9ZXDiDd9AOnHI0dSg0jo334hz7oy65kSp/xIGDtFYwRo98LPIjvkns0mRszwzLTzAv7IhvakZT9tkebhQokrSsAopLMCBu44BRmCSt8pi5ViEgXM98D5h2VPWUMOkXsoazPyL6ElTTSeaPQSuD1SAcV5CC8aX66Ha06CEF1Gt/2IBILTbErm6RaLBar05KyWvdptmqjaxgzt1jaI4VwNZWizwTrw0l4jJw/NLF80m9rmYaMOhLAEx9zdWJpnyvlb90KjmUhptyRNzlVfyDEhiwA0VQ2Eu0XucWyJ0UncPhaPVYAcX4NM+UJoMavpkboTotib4BZtHQISOMaYnCvz4k/0rxsrTzOLjuFs47WyLb2nqLXKiHeGSrQ0o7PNaBLy8QdiO++FqG1lQwUKG7fvL7U6A8fClCIjGN1bNz3UYZp1Sw84LlI+ICrLbcv2aDTiQADyq+N5TSS3ccxq499rDkSBpIyPulKDPBLLZOv6fZ9T9uhKTL0+NY=
    admin-user: AgAIBlrCtHTnfkkhSkQmmcjVNvaoDXrE+3cIRoecGKENJOvrT0l5LK8Go2evsUCo8qwbfyj2AwQ1PaFcOViMw1Csfn8KMfubKVKyG8dAVBqf3IUIZZrNKWS50nFU/a0pGVhQR+f8TOEFCPD9KDftbvlalrJoyv8FPTv5zEA6JB3kxzIrYqqj/3IOGpg4oghpYDZwCeKdsQBmpKfNG1DU+Z88t2KDWUq3udYJvp6eZXTr+Zp0BLL/FRn2db/1xf94AsciMJrp7+WUJ2+DTWZ8O11x3ffRCgkeB5727rqpT219H6/VA55sVvuScpLbGMRKGJWgYQ33zaMozuc+XWu0LNoea1DjnuBkJOvuDg+S/GGMzY13uCPxa7C1e0NF/ulbYTQ6AvqzbGrFSLKZizXXkhUHiRPMzxnzzQ8dJmtLx1quXJnyWzMr+ljOPqhq0V4+lz5/sOuMHqx5bjEs50W5mG2p8AD1OPyAYZwwqsVGbiuCalP/cT9TcpCw6t/RPKZn4jeino16Jc6fSK90UpqQZ/aOWLd9j1POgSF0Xw7fJK3lsoAGFNYBY6J7XrYreZVMLuFGBBlLfWUOLHyJGOcGeHfscHFhHhxTE4Qo/UC46O5FxTZDJTiECOuFuvfUnPUqk8sa0dok3Nzs7JUc2KQpBXS8ga22GLniuO2S+rHVTl3eVzbz1fXz2dGfUXqiZ1DrLnZ3Thyt
